# Generated by Django 4.2.5 on 2023-09-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sedimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(max_length=100)),
                ('capacidade', models.CharField(max_length=100)),
                ('tempo_sedimentacao', models.CharField(max_length=100)),
                ('nivel_tanque', models.CharField(max_length=100)),
                ('etapa', models.CharField(max_length=100)),
                ('viscosidade', models.CharField(max_length=100)),
                ('tempo_estimado', models.CharField(max_length=100)),
            ],
        ),
    ]
