# Generated by Django 4.2.4 on 2023-09-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoativacao',
            name='ajuste_pH_ativado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicoativacao',
            name='coagulacao_ativada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicoativacao',
            name='floculacao_ativada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicoativacao',
            name='precipitacao_ativada',
            field=models.BooleanField(default=False),
        ),
    ]
