# Generated by Django 4.2.5 on 2023-09-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sedimentacao',
            name='tempo_sedimentacao',
        ),
        migrations.AlterField(
            model_name='sedimentacao',
            name='capacidade',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='sedimentacao',
            name='etapa',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='sedimentacao',
            name='nivel_tanque',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='sedimentacao',
            name='processo',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='sedimentacao',
            name='tempo_estimado',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='sedimentacao',
            name='viscosidade',
            field=models.CharField(max_length=250),
        ),
    ]
