# Generated by Django 4.2.4 on 2023-09-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicoativacao_ajuste_ph_ativado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaCoagulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TanqueAjustePH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeFloculacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadePrecipitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicoativacao',
            name='ajuste_pH_ativado',
        ),
        migrations.RemoveField(
            model_name='historicoativacao',
            name='coagulacao_ativada',
        ),
        migrations.RemoveField(
            model_name='historicoativacao',
            name='floculacao_ativada',
        ),
        migrations.RemoveField(
            model_name='historicoativacao',
            name='precipitacao_ativada',
        ),
    ]
