# Generated by Django 4.2.3 on 2023-09-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dados'),
    ]

    operations = [
        migrations.CreateModel(
            name='dados1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dado1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dados2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dado2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dados3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dado3', models.CharField(max_length=100)),
            ],
        ),
    ]
