# Generated by Django 4.2.5 on 2023-09-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sedimentacao_capacidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedimentacao',
            name='capacidade',
            field=models.IntegerField(),
        ),
    ]
